sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - npm i -g npm@^4.0.0
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test:coverage
after_success:
  - npm run semantic-release
after_script:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - master
  - /^greenkeeper/.*$/
